const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#E31E24",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#E31E24",
    primaryForeground: "#FFFFFF",
    secondary: "#222222",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#C9A227",
    accentForeground: "#000000",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A2A",
    input: "#1A1A1A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#E31E24",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#E31E24",
    primaryForeground: "#FFFFFF",
    secondary: "#222222",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#C9A227",
    accentForeground: "#000000",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A2A",
    input: "#1A1A1A",
  },
  radius: 12,
};

export default colors;
